chore: fix ci tests
explay-io/ui_kit pull request #15
Opened 2021-03-29 01:11 UTC by andywindowsmac

2021-04-02 08:22 UTC, almeynman requested changes

2021-04-02 08:22 UTC, almeynman commented on lib/inputs/pin_view_test.dart
> +      // ignore: invalid_use_of_visible_for_testing_member
Couldn't find what this rule is about... is it because the file is not in the `test` directory? If yes, then probably need to specify it in some config or disable the rule completely

2021-04-02 08:22 UTC, almeynman commented on coverage/lcov.info
> +SF:lib/badges/badge.dart
git ignore coverage folder

2021-04-05 07:44 UTC, andywindowsmac commented on lib/inputs/pin_view_test.dart
> +      // ignore: invalid_use_of_visible_for_testing_member
https://uniteamou.atlassian.net/browse/UO-30?atlOrigin=eyJpIjoiNDJkYjFjZmE1MzY1NDYxMjg1ZTcyMTBjYTU2ZGRlNDIiLCJwIjoiaiJ9

2021-04-06 12:21 UTC, almeynman approved these changes

2021-04-06 12:21 UTC, merged