Uo 3/remove text reference change
explay-io/ui_kit pull request #7
Opened 2021-03-23 13:30 UTC by andywindowsmac

2021-03-23 14:21 UTC, almeynman requested changes
Also in currency display please change bitcoin to euros

2021-03-23 14:21 UTC, almeynman commented on lib/stories/cards.dart
> +              'Some news',
can we have some longer text with lorem ipsum and a square image, so that the use case is clear

2021-03-23 14:21 UTC, almeynman commented on lib/stories/info_box.dart
> +            'infoBody': 'Body'
lorem ipsum pls, looks ugly like when it's short

2021-03-23 14:21 UTC, almeynman commented on lib/stories/layouts.dart
> +                        'Get the latest version of the app.',
Can you please also change text in information template to lorem ipsum, can't add a comment there

"To verify your account, we need you to submit another identity document, alongside with your residence permit.\n\nYou can submit a photo of your passport, national ID, or drivers’ license."

2021-03-23 14:21 UTC, almeynman commented on lib/stories/layouts.dart
> +                                        'Add Euro to your account.',
"I\'m all about that payment methods" -> "Choice template"
"Add Euro to your account." -> Lorem ipsum
"I want to deposit" -> Lorem ipsum

2021-03-23 14:21 UTC, almeynman commented on lib/stories/layouts.dart
> +                                      'CNG tokens give you the right to become shareholder',
Change all to lorem ipsum

2021-03-24 04:58 UTC, andywindowsmac commented on README.md
>  #Principles
done

2021-03-24 04:58 UTC, andywindowsmac commented on lib/stories/cards.dart
> +              'Some news',
changes almost everywhere

2021-03-24 08:24 UTC, almeynman requested changes
![image](https://user-images.githubusercontent.com/6459157/112278021-0c526000-8c8b-11eb-94ff-42dab39bb022.png)
вот это только осталось

2021-03-24 09:07 UTC, almeynman approved these changes

2021-03-24 09:29 UTC, merged